### ISSUE TITLE
Document variants

### ISSUE THREAD

**Issue by meeDamian** [lncm/docker-lnd#24]
Create a central place documenting all built variants.

Probably the best way would be a file along these lines:

```yml
versions:
  v0.8.1:
    changelog: Changelog URL
    description: Our optional brief description of the version

variants:
  monitoring:
    description: Our description of a variant
    only:
      - limit variant to these versions only (ex. `-bitcoind0.19` variant is only useful for `lnd v0.8.0`)
  
  experimental:
    …
```

Such file would also be useful to generating Github Release descriptions, as well as `README.md` list of tags.
